services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    ports:
      - "80:80"          # Expose port 80 for HTTP traffic
      - "443:443"        # Expose port 443 for HTTPS traffic
    volumes:
      - /home/$USER/data/website:/var/www/html
    restart: always
    depends_on:
      - wordpress
      - mariadb
    networks:
      - container

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    ports: 
      - "3306:3306"
    networks:
      - container
    restart: always
    volumes:
      - /home/$USER/data/database:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    env_file:
      .env
    ports:
      - "9000:9000"
    volumes:
      - /home/$USER/data/website:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - container

networks:
  container: