services:
  nginx:
    container_name: nginx
    hostname: nginx
    build: requirements/nginx/
    ports:
      - "443:443"        # Expose port 443 for HTTPS traffic
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    hostname: mariadb
    build: requirements/mariadb/
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    hostname: wordpress
    build: requirements/wordpress/
    env_file:
      .env
    volumes:
      - wordpress:/var/www/html
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  mariadb:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/database
  wordpress:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress